### ISSUE TITLE
Implement the blockIndex type of module

### ISSUE THREAD

**Issue by sduchesneau** [streamingfast/substreams#411]
# Specs
* This module type has no params in its input, has no "initialBlock" and no "output".
* The code for this type of module will simply return an array of strings for a given block.
Ex: input (block or mapper...)  --> output []string
* The output will be saved to disk in a special format using "roaring bitmaps". See https://github.com/streamingfast/bstream/blob/develop/transform/block_indexer.go for an example implementation (or copy it blatantly)

# Dependencies

* This depends on  proto definitions from #410

# TODO
- [x] make substreams add the indexing module as a dependency in the module tree if a module depends on it through a "blockFilter" parameter.
- [x] Write the code to execute that type of module and gather its outputs 
- [x] Write the code to write all those outputs in a roaring bitmap format for the processed range (on tier2)

(this issue does not include the "read" part, i.e. using the index.)

**Comment by sduchesneau** [comment]
Shipped in https://github.com/streamingfast/substreams/releases/tag/v1.6.0
